### PR TITLE
Improve user interaction pattern for date inputs

### LINKED ISSUE #91: Improve display of date fields
## Is your feature request related to a problem? Please describe.
The current display of date fields is potentially really confusing to a user. Are there ways we can improve the interaction pattern or display to make things easier on users? 

Screen Shot 2021-02-25 at 12 01 29 PM

## Describe the solution you'd like
Potential solution:
- Instead of displaying all the date inputs, display a select for both start date and end date. 
- For start date, the options would be:
  - "This restriction starts on a specific date" - if selected, displays the start_date field
  - "This restriction starts after an embargo period" - if selected, displays the start_date_period
- For end date, the options would be:
  - "This restriction ends on a specific date" - if selected, displays the end_date field
  - "This restriction ends after an embargo period" - if selected, displays the end_date_period
  - "There is no end date for this restriction" - doesn't display any input but the end_date_open boolean would be checked

One advantage to an approach like this is that it would make validation a lot easier. 

Are there accessibility implications of this kind of pattern?

## Additional context
Noting this was also an issue identified (but not fully solved) in Aurora testing.

### PR DESCRIPTION
**Pull request by helrond**
Adds date inputs as specified in #91. This should be a little easier for users to work with, and substantially simplifies the UI as well as validation.

I'm interested in whether having some form layouts in Crispy Form Layouts and some in regular Django templates is confusing/causes maintenance issues. If so, I think I would argue for us just dropping everything into Django templates, and shedding crispy as a dependency.

Not covered in this PR - date inputs are not consistently structured, and behave differently. We should fix that, see #99

This also presumes that #98 will be merged first.

fixes #91

### CODE REVIEW

**Comment by bonniegee** [comment]
I think this approach looks really great, and it also obviates (or in a way, fixes) #67.

One buggy behavior I've noticed is that when a Start Date Embargo Period is 0 (and the record is saved), that start date totally disappears when going to the edit page.

**Comment by helrond** [comment]
@bonniegee thanks - let me look at that. 

In terms of validation, there are certain scenarios this won't cover, like an end date being after a start date. But I think it will take care of the basic "is there one and only one value here" validation.

**Comment by bonniegee** [comment]
I'm trying to think through whether having the end date before the start date would cause issues (i.e., cause an app to blow up) downstream--I think the answer is "no," but it might be worth keeping this scenario in mind as we work on back end development.

**Comment by helrond** [comment]
OK - I mean, let's do what we need to do so we get good data! All I'm saying is that I think #67 may need to be rescoped.

**Review by bonniegee — APPROVED** [review]
This looks ✨! 

Something to keep an eye out for in usability testing--I think the "embargo" language could possibly be confusing for copyright bases.

**Review by HaSistrunk — APPROVED** [review]

**Pull request merged**
