### PR TITLE
Prevent rights basis type from changing, only show relevant fields for rights basis on detail page

### PR DESCRIPTION
**Pull request by bonniegee**
Splits create and update templates so the update page only renders fields for the rights basis of the rights shell and disables editing the rights basis. In order to disable the rights basis field on the edit page, I created a new form to disable that field in a widget.

The code to render specific forms in the update view is pretty verbose, but I was having issues trying to make it more concise.

### CODE REVIEW

**Comment by bonniegee** [comment]
Adding that this fixes #64 and #65

**Comment by helrond** [comment]
One thing you could do to make the views a little more concise is factor out a `get_formclass` method which takes a rights basis and returns the form class you want, something like:

```
def get_formclass(self, rights_basis):
  if rights_basis == "Copyright":
    form_cls = CopyrightForm.
...
  return form_cls
```

Then you could use it in your views like:

```
cls = self.get_formclass(context["object"].rights_basis)
context["basis_form"] = cls(self.request.POST, instance=self.object)
```

That would cut down on doing the same logic twice at least.

You could also create a static dictionary that references form classes by rights bases:

```
FORMS = {"copyright": Copyright}
```
And you'd use that like

```
cls = FORMS[context["object"].rights_basis]
...
```

I'm not sure one is objectively better than the other; it's a matter of preference and what you think is easier to read.

**Comment by bonniegee** [comment]
Outstanding issue with this PR: while the correct form type shows on the edit page, the edit page cannot be saved and is throwing a "this field is required" error for rights basis.

**Comment by helrond** [comment]
@bonniegee this is ready for review. Since you submitted the PR I can't explicitly add you as a reviewer...

**Review by bonniegee — COMMENTED** [review]
This looks good to me! The `form_cls` function makes a ton of sense. (I can't approve this since it's "my" PR.)

**Review by HaSistrunk — APPROVED** [review]
Looks good to me!

**Pull request merged**
